services:
  backend:
    build: 
      context: ./food_db
      dockerfile: django.Dockerfile
    container_name: food-db-django
    restart: always
    volumes:
      - ./food_db/db_data:/app/db_data
      - ./food_db/food_db_app:/app/food_db_app
      - ./food_db/static:/app/static
    ports:
      - "8000:8000"
    # healthcheck:
    #   test: ["CMD", "mysql", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
    #   timeout: 20s
    #   retries: 10
  ingredient_parse:
    build: 
      context: ./ingredient_parse
      dockerfile: ingred.Dockerfile
    container_name: food-db-ingred
    restart: always
    # volumes:
    #   - ./ingredient_parse/parse_api:/app/parse_api
    ports:
      - "5000:5000"
    # healthcheck:
    #   test: ["CMD", "mysql", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
    #   timeout: 20s
    #   retries: 10