from django import template
from django.utils.text import slugify
import re

import markdown as md

register = template.Library()

@register.simple_tag
def markdown(step_id, value, recipe_title, multiplier=1):
    # Process custom ingredient links before passing to markdown
    processed_value = render_ingredient_links(step_id, value, multiplier)
    html = md.markdown(processed_value, extensions=['markdown.extensions.fenced_code'])
    # Add IDs to headings for anchor links
    html = add_heading_ids(html)
    return html

def render_ingredient_links(step_id, text, multiplier):
    """
    Render custom ingredient links by looking up pre-created LinkedIngredient records.
    
    LinkedIngredient records are created at recipe add/edit time by identify_ingredient_links().
    This function matches regex patterns to LinkedIngredients by order of appearance, verifies
    the ingredient name matches, and renders HTML spans with tooltip data.
    
    Args:
        step_id: The ID of the RecipeStep
        text: The step description text containing ingredient link syntax
        multiplier: The quantity multiplier for ingredient amounts
    
    Returns:
        str: The text with ingredient links replaced by HTML spans
    """
    # Import here to avoid circular imports
    from food_db_app.models import LinkedIngredient
    from food_db_app.views import RecipeIngredientData
    from food_db_app.views.utils import INGREDIENT_LINK_PATTERN
    
    # Fetch all LinkedIngredients for this step, ordered by appearance
    linked_ingredients = list(
        LinkedIngredient.objects.filter(step_id=step_id)
        .select_related('ingredient', 'ingredient__food', 'ingredient__unit_of_measurement')
        .order_by('order_in_step')
    )
    
    # Track which LinkedIngredient we're on
    link_index = 0
    
    def replace_ingredient_link(match):
        nonlocal link_index
        
        link_text = match.group(1)
        parentheses_clause = match.group(2)
        parsed_ingredient_name = match.group(3)
        
        # Determine the expected ingredient name from the syntax
        if not parentheses_clause:
            expected_food_name = link_text
        else:
            expected_food_name = parsed_ingredient_name.strip()
        
        # Check if we have a LinkedIngredient for this position
        if link_index >= len(linked_ingredients):
            # No LinkedIngredient found for this match - ingredient lookup failed at save time
            link_index += 1
            return link_text + ' <linked ingredient not found>'
        
        linked_ingredient = linked_ingredients[link_index]
        ingredient = linked_ingredient.ingredient
        
        # Verify the ingredient name matches what we expect
        if ingredient.food.name.lower() != expected_food_name.lower():
            # Mismatch - the step text may have been modified or LinkedIngredients are stale
            link_index += 1
            return link_text + ' <ingredient link mismatch>'
        
        # Build the tooltip content
        quantity = RecipeIngredientData.stringify_ingredient_quantity(
            ingredient.quantity,
            ingredient.unit_of_measurement.name if ingredient.unit_of_measurement else '',
            multiplier
        )
        ingredient_name = ingredient.food.name
        
        tooltip_content = f'{quantity} {ingredient_name}'
        
        if ingredient.quantity != 1 and not ingredient.unit_of_measurement and not ingredient_name.endswith('s'):
            tooltip_content += 's'
        
        if ingredient.notes:
            tooltip_content += f' - {ingredient.notes}'
        
        link_index += 1
        
        # Return HTML span with tooltip attributes
        return f'<span class="ingredient_link" data-ingredient_id="{ingredient.id}" data-tooltip="{tooltip_content}">{link_text}</span>'
    
    return re.sub(INGREDIENT_LINK_PATTERN, replace_ingredient_link, text, flags=re.IGNORECASE)

def add_heading_ids(html):
    """
    Add ID attributes to heading elements (h1-h6) so anchor links work.
    IDs are generated by slugifying the heading text.
    """
    def add_id_to_heading(match):
        tag = match.group(1)  # h1, h2, h3, etc.
        existing_attrs = match.group(2) or ''  # Any existing attributes
        heading_content = match.group(3)  # The content of the heading (may include nested tags)
        
        # Extract text content from heading for ID generation (strip HTML tags)
        heading_text = re.sub(r'<[^>]+>', '', heading_content).strip()
        
        # Generate ID from heading text
        heading_id = slugify(heading_text)
        
        # If heading already has an ID, keep it; otherwise add the generated one
        if 'id=' in existing_attrs:
            return match.group(0)  # Return unchanged if ID already exists
        else:
            # Add id attribute
            if existing_attrs:
                return f'<{tag} id="{heading_id}" {existing_attrs}>{heading_content}</{tag}>'
            else:
                return f'<{tag} id="{heading_id}">{heading_content}</{tag}>'
    
    # Pattern to match h1-h6 tags with optional attributes and any content (including nested tags)
    # Uses non-greedy match to handle nested tags
    pattern = r'<(h[1-6])([^>]*)>(.*?)</\1>'
    return re.sub(pattern, add_id_to_heading, html, flags=re.DOTALL)