from django import template
from django.utils.text import slugify
import re

import markdown as md

register = template.Library()

@register.simple_tag
def markdown(step_id, value, recipe_title, multiplier=1):
    """
    Template tag to render step description with ingredient links and markdown formatting.
    
    Flow:
    1. Look up the RecipeStep and render ingredient links (<!ID> → HTML spans)
    2. Apply markdown formatting to the result
    3. Add IDs to headings for anchor links
    
    Note: value and recipe_title parameters are kept for backward compatibility but
    the step is looked up by step_id to get the processed description.
    """
    from food_db_app.models import RecipeStep
    
    # Get the step and render ingredient links
    step = RecipeStep.objects.get(id=step_id)
    text_with_rendered_links = step._render_ingredient_links(multiplier)
    
    # Apply markdown formatting
    html = md.markdown(text_with_rendered_links, extensions=['markdown.extensions.fenced_code'])
    
    # Add IDs to headings for anchor links
    html = add_heading_ids(html)
    
    return html

def add_heading_ids(html):
    """
    Add ID attributes to heading elements (h1-h6) so anchor links work.
    IDs are generated by slugifying the heading text.
    """
    def add_id_to_heading(match):
        tag = match.group(1)  # h1, h2, h3, etc.
        existing_attrs = match.group(2) or ''  # Any existing attributes
        heading_content = match.group(3)  # The content of the heading (may include nested tags)
        
        # Extract text content from heading for ID generation (strip HTML tags)
        heading_text = re.sub(r'<[^>]+>', '', heading_content).strip()
        
        # Generate ID from heading text
        heading_id = slugify(heading_text)
        
        # If heading already has an ID, keep it; otherwise add the generated one
        if 'id=' in existing_attrs:
            return match.group(0)  # Return unchanged if ID already exists
        else:
            # Add id attribute
            if existing_attrs:
                return f'<{tag} id="{heading_id}" {existing_attrs}>{heading_content}</{tag}>'
            else:
                return f'<{tag} id="{heading_id}">{heading_content}</{tag}>'
    
    # Pattern to match h1-h6 tags with optional attributes and any content (including nested tags)
    # Uses non-greedy match to handle nested tags
    pattern = r'<(h[1-6])([^>]*)>(.*?)</\1>'
    return re.sub(pattern, add_id_to_heading, html, flags=re.DOTALL)