# Generated by Django 5.1 on 2024-09-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_recipe_food_category',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
