# Generated by Django 5.1 on 2024-09-16 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0003_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookedmeal',
            name='date_cooked',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
