# Generated by Django 5.1 on 2024-09-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0003_alter_ingredient_unit_of_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_book',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_book_page',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
