# Generated by Django 5.1 on 2024-09-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0004_recipe_recipe_book_recipe_recipe_book_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_book',
        ),
        migrations.CreateModel(
            name='RecipeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('_date_created', models.DateTimeField(auto_now_add=True)),
                ('_date_modified', models.DateTimeField(auto_now=True)),
                ('recipes', models.ManyToManyField(blank=True, related_name='recipe_book', to='food_db_app.recipe')),
            ],
        ),
    ]
