# Generated by Django 5.1 on 2024-09-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0004_alter_cookedmeal_date_cooked'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='clean_key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='clean_key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipebook',
            name='clean_key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unitofmeasurement',
            name='clean_key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
