# Generated by Django 5.1 on 2024-09-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0005_food_clean_key_recipe_clean_key_recipebook_clean_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='clean_key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='clean_key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='recipebook',
            name='clean_key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='unitofmeasurement',
            name='clean_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
