# Generated by Django 5.1 on 2024-09-11 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0005_remove_recipe_recipe_book_recipebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipebook',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_db_app.recipebook'),
        ),
    ]
