# Generated by Django 5.1 on 2024-09-24 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0006_alter_food_clean_key_alter_recipe_clean_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookedmeal',
            name='date_cooked',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
