# Generated by Django 5.1 on 2024-09-24 04:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0008_alter_cookedmeal__date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookedmeal',
            name='_date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cookedmeal',
            name='date_cooked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
