# Generated by Django 5.1 on 2024-10-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0009_alter_cookedmeal__date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='calories_per_serving',
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories_per_recipe',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
