# Generated by Django 5.1 on 2025-03-17 15:55

import food_db_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0011_recipeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimage',
            name='_file_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(upload_to=food_db_app.models.PathAndRename('images/recipes/')),
        ),
    ]
