# Generated by Django 5.1 on 2025-03-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0012_recipeimage__file_name_alter_recipeimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_category_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
