# Generated by Django 5.1 on 2025-03-20 01:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0012_recipeimage__file_name_alter_recipeimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('order_number', models.PositiveSmallIntegerField()),
                ('_date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('_date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_db_app.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_category_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_db_app.ingredientcategory'),
        ),
        migrations.AddConstraint(
            model_name='ingredientcategory',
            constraint=models.UniqueConstraint(fields=('recipe', 'name'), name='unique_recipe_ingredient_category_name'),
        ),
    ]
