# Generated by Django 5.1 on 2025-03-20 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0013_ingredientcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_category',
        ),
    ]
