# Generated by Django 5.1 on 2025-03-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0013_ingredient_ingredient_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_category_order',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
