# Generated by Django 5.1 on 2025-03-20 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0014_remove_ingredient_ingredient_category'),
    ]

    operations = [
        migrations.RenameField('ingredient','ingredient_category_test','ingredient_category'),
    ]