# Generated by Django 5.1 on 2025-03-21 20:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0015_remove_ingredient_ingredient_category_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('_date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('_date_modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='qfc_aisle',
        ),
        migrations.AddField(
            model_name='food',
            name='food_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='food_db_app.foodcategory'),
        ),
    ]
