# Generated by Django 5.1 on 2025-03-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0016_foodcategory_remove_food_qfc_aisle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
