# Generated by Django 5.1 on 2025-04-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0017_alter_food_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientcategory',
            constraint=models.CheckConstraint(condition=models.Q(('name__exact', 'Misc'), _negated=True), name='recipe_ingredient_category_name_not_misc'),
        ),
    ]
