# Generated by Django 5.1 on 2025-06-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0018_ingredientcategory_recipe_ingredient_category_name_not_misc'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_baking_recipe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_baking_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_cooking_tag',
            field=models.BooleanField(default=True),
        ),
    ]
