# Generated by Django 5.1 on 2025-06-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0019_recipe_is_baking_recipe_tag_is_baking_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='child_recipes',
            field=models.ManyToManyField(blank=True, to='food_db_app.recipe'),
        ),
    ]
