# Generated by Django 5.1 on 2025-06-27 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0020_recipe_child_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='child_recipes',
        ),
    ]
