# Generated by Django 5.1 on 2025-06-27 02:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0021_remove_recipe_child_recipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentChildRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveSmallIntegerField(default=0, help_text='Order number for the child recipe when displayed on page for parent recipe. Lower numbers appear first.')),
                ('_date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('child_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_db_app.recipe')),
                ('parent_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relationship', to='food_db_app.recipe')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('parent_recipe', 'child_recipe'), name='unique_parent_child_recipe')],
            },
        ),
    ]
