# Generated by Django 5.1 on 2025-06-27 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0022_parentchildrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentchildrecipe',
            name='child_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationship', to='food_db_app.recipe'),
        ),
    ]
