# Generated by Django 5.1 on 2025-07-06 18:56

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0023_alter_parentchildrecipe_child_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='border_color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='tag',
            name='fill_color',
            field=colorfield.fields.ColorField(default='#3cc382', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='tag',
            name='has_border',
            field=models.BooleanField(default=False, help_text='Whether the tag has a border or not'),
        ),
        migrations.AddField(
            model_name='tag',
            name='text_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
    ]
