# Generated by Django 5.1 on 2025-09-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0025_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_component_recipe',
            field=models.BooleanField(default=False),
        ),
    ]
