# Generated by Django 5.1 on 2025-10-26 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0026_recipe_is_component_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeTimingAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bake', 'Bake'), ('chill', 'Chill'), ('prove', 'Prove'), ('simmer', 'Simmer'), ('marinade', 'Marinade'), ('rest', 'Rest')], max_length=15)),
                ('minutes', models.PositiveSmallIntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_db_app.recipe')),
            ],
        ),
    ]
