# Generated by Django 5.1 on 2025-10-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0027_recipetimingattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='oven_temp',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
