# Generated by Django 5.1 on 2025-10-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0028_recipe_oven_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cookie_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cookie_style',
            field=models.CharField(blank=True, choices=[('hand_rolled', 'Hand-rolled'), ('slice_n_bake', "Slice 'n Bake"), ('cut', 'Cut'), ('stamped', 'Stamp')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_cookie_recipe',
            field=models.BooleanField(default=False),
        ),
    ]
