# Generated by Django 5.1 on 2025-10-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0029_recipe_cookie_color_recipe_cookie_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetimingattribute',
            name='type',
            field=models.CharField(choices=[('bake', 'Bake'), ('chill', 'Chill'), ('prove', 'Prove'), ('simmer', 'Simmer'), ('marinade', 'Marinade'), ('cool', 'Cool')], max_length=15),
        ),
    ]
