# Generated by Django 5.1 on 2025-11-06 02:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0030_alter_recipetimingattribute_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('selected_fields', models.JSONField(default={'recipe_attributes': {}, 'tags': []})),
                ('_date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('_date_modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories_per_recipe',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total Calories'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cookie_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cookie Color'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cookie_style',
            field=models.CharField(blank=True, choices=[('hand_rolled', 'Hand-rolled'), ('slice_n_bake', "Slice 'n Bake"), ('cut', 'Cut'), ('stamped', 'Stamp')], max_length=20, null=True, verbose_name='Cookie Style'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_component_recipe',
            field=models.BooleanField(default=False, verbose_name='Component of a Larger Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_cookie_recipe',
            field=models.BooleanField(default=False, verbose_name='Cookies'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='oven_temp',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Oven Temperature'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_db_app.recipebook', verbose_name='Recipe Book'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_book_page',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Recipe Book Page'),
        ),
    ]
