# Generated by Django 5.1 on 2025-11-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0031_viewconfig_alter_recipe_calories_per_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewconfig',
            name='selected_fields',
            field=models.JSONField(default={'recipe_attributes': [], 'tags': []}),
        ),
    ]
