# Generated by Django 5.1 on 2025-11-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0032_alter_viewconfig_selected_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentchildrecipe',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('component', 'Component'), ('variant', 'Variant')], max_length=15, null=True),
        ),
    ]
