# Generated by Django 5.1 on 2025-11-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0033_parentchildrecipe_relationship_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentchildrecipe',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('component', 'Component'), ('base', 'Base')], max_length=15, null=True),
        ),
    ]
