# Generated by Django 5.1

import food_db_app.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0034_alter_parentchildrecipe_relationship_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeImageTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_clean_key', models.CharField(help_text='Clean key of the recipe this image belongs to (recipe may not exist yet)', max_length=255)),
                ('image', models.ImageField(upload_to=food_db_app.models.PathAndRename('images/recipes/'))),
                ('_file_name', models.CharField(blank=True, max_length=300, null=True)),
                ('_date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]

