# Generated by Django 5.1 on 2026-02-03 02:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0036_recipeimagetemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_in_step', models.PositiveSmallIntegerField(help_text='The order this link appears in the step text (0-indexed).')),
                ('raw_input', models.TextField(help_text="The original text the user entered (e.g., '[butter]' or '[butter](!salted butter;dairy)').")),
                ('link_text', models.CharField(help_text="The visible text in the rendered link (e.g., 'butter').", max_length=255)),
                ('_date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_links', to='food_db_app.ingredient')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_ingredients', to='food_db_app.recipestep')),
            ],
        ),
    ]
