# Generated by Django 5.1 on 2025-03-21 20:15

import re
from django.db import migrations
from food_db_app.views.utils import process_ingredient_links, create_linked_ingredients_for_step, RESERVED_SYNTAX_PATTERN
from food_db_app.models import RecipeStep


def update_step_descriptions(apps, schema_editor):
    for step in RecipeStep.objects.select_related('recipe').all():
        # Skip blank steps
        if not step.description or not step.description.strip():
            continue
        
        # Skip already processed steps
        if re.search(RESERVED_SYNTAX_PATTERN, step.description):
            continue
        
        processed_description, linked_ingredient_data = process_ingredient_links(
            step.description,
            step.recipe.title
        )
        
        if linked_ingredient_data:
            step.description = processed_description
            step.save()
            create_linked_ingredients_for_step(step, linked_ingredient_data)


class Migration(migrations.Migration):

    dependencies = [
        ('food_db_app', '0037_linkedingredient'),
    ]

    operations = [
        migrations.RunPython(update_step_descriptions, reverse_code=migrations.RunPython.noop),
    ]
